version: 2

#mkdocs:
#  configuration: mkdocs.yml
#  fail_on_warning: false

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: false

python:
  version: 3.7
  install:
    - requirements: requirements.txt

formats:
  - pdf