site_name: C++编程风格指南
theme: readthedocs
nav:
- 译者前言: 
    - 内容简介: translator_introduction.md
    - 注意事项: translator_caution.md
- 正文: 
    - 1 简介: 1_introduction.md
    - 2 整体建议: 2_general_recommendations.md
    - 3 命名规范: 3_naming_conventions.md
    - 4 文件: 4_files.md
    - 5 语句: 5_statements.md
    - 6 布局和注释: 6_layout_comments.md
    - 7 参考文献: 7_reference.md
- 译者附录: translator_appendix.md
repo_url: https://github.com/Guoning-Chen/Cpp-Programming-Style-Guideline